spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/epicentro_gourmet
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "1234"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  thymeleaf:
    cache: false
